# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalStb',
            fields=[
                ('mac_address', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'PHYSICAL_STB',
            },
        ),
        migrations.CreateModel(
            name='Stb',
            fields=[
                ('stb_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('iptv_status_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'STB',
            },
        ),
        migrations.AddField(
            model_name='physicalstb',
            name='stb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stb', to='user.Stb'),
        ),
    ]
