# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stb_id', models.CharField(max_length=60)),
                ('mac_addr', models.CharField(max_length=30)),
                ('iptv_status_code', models.CharField(max_length=10)),
            ],
        ),
    ]
